version: "3.7"

services:
  goblog:
    image: hzget/goblog:1.1
    entrypoint: ["/app/goblog"]
    depends_on:
      - mysql
      - redis
      - analysis
    ports:
      - 8080:8080
    # for the debug mode, programmer can uncomment corresponding lines
#    volumes:
#      - ./blog/config:/app/blog/config
#      - ./:/app

  mysql:
    image: mysql:8.0.27
    volumes:
      - goblog-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
      MYSQL_DATABASE: blog

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    volumes:
      - goblog-redis-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  analysis:
    image: hzget/analysis:latest
    entrypoint: ["python", "analysis_server.py"]

volumes:
  goblog-mysql-data:
  goblog-redis-data:
